# This field keeps the timestamp of when 'repo bootstrap' was executed.
# This timestamp is being used by the pre-push hook to check only the commits
# that happened after so that it is easier to migrate existing projects to SF.
# You can modify the timestamp manually in case there is a need.
salsaflow_enabled_timestamp: "2015-02-17T12:36:11.142902641+01:00"

#issue_tracker: "jira"
#jira:
#  server_url: "https://jira.salsitasoft.com"
#  project_key: "SFT"
issue_tracker: "pivotal_tracker"
pivotal_tracker:
  project_id: 525465
#issue_tracker: "sprintly"
#sprintly:
#  product_id: 27068

code_review_tool: "review_board"
review_board:
  server_url: "https://review.salsitasoft.com"
#code_review_tool: "github"
