# This field keeps the timestamp of when 'repo bootstrap' was executed.
# This timestamp is being used by the pre-push hook to check only the commits
# that happened after so that it is easier to migrate existing projects to SF.
# You can modify the timestamp manually in case there is a need.
salsaflow_enabled_timestamp: "2015-02-17T12:36:11.142902641+01:00"

versioning:
  trunk_suffix:   "trunk"
  testing_suffix: "testing"
  stage_suffix:   "client"

#issue_tracker:
#  module_id: "JIRA"
#  module_config:
#    server_url: "https://jira.salsitasoft.com"
#    project_key: "SFT"
issue_tracking:
  module_id: "salsaflow.issuetracking.pivotaltracker"
  module_config:
    project_id: 525465
  
#code_review:
#  module_id: "Review Board"
#  module_config:
#    server_url: "https://review.salsitasoft.com"
code_review:
  module_id: "salsaflow.codereview.github"

release_notes:
  module_id: "salsaflow.releasenotes.github"
