issue_tracker: "jira"
jira:
  server_url: "https://jira.salsitasoft.com"
  project_key: "SFT"
#issue_tracker: "pivotal_tracker"
#pivotal_tracker:
#  project_id: 525465

code_review_tool: "review_board"
review_board:
  server_url: "https://review.salsitasoft.com"
