package metadata

/*****************************************
 * This file was generated by SalsaFlow. *
 * Please do not modify it manually.     *
 *****************************************/

const Version = "0.25.0-trunk"
